name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up Python 3
        uses: actions/setup-python@main
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: curl https://install.python-poetry.org | python -

      - name: Install dependencies
        run: poetry install

      - name: Run black
        run: poetry run python -m black --check --diff .

      - name: Run isort
        run: poetry run python -m isort --check-only --diff .

      - name: Run pyright
        run: poetry run python -m pyright --warnings
